### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by jhelwig** [cheef/shell-spinner#1]
Under which license (or licenses) is this available?  I'm afraid I couldn't find which license this is published under from poking around the `README` or `.gemspec`.

**Comment by bazay** [comment]
Hi @jhelwig, it appears this gem requires a dependency gem `colorize` for which the license is **GNU GPL** License. 

I've created a PR to add this gem to the **MIT License** so hopefully @cheef is okay with such a license.
